In [ ]:
from google.colab import files
uploaded = files.upload()

Saving baseline_behavior.csv to baseline_behavior.csv

In [ ]:
import pandas as pd

# Behavior

In [ ]:
behavior = pd.read_csv('/content/baseline_behavior.csv')
behavior.head(12)

,Unnamed: 0,user_id,date,Running,Stationary,Unknown,Walking,dist_total_km,dist_mean_km,dist_std_km,...,Running_mean,Running_std,sleep_duration_z,dist_total_km_z,conversation_count_z,total_conversation_minutes_z,num_bt_devices_z,Stationary_z,Walking_z,Running_z
0,0,u00,2013-03-27,0.046536,0.812952,0.030422,0.110090,65.395914,1.127516,3.644554,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,u00,2013-03-28,0.022662,0.910270,0.017029,0.050039,167.400792,2.461776,5.293769,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,u00,2013-03-29,0.013046,0.838184,0.034370,0.114400,110.812228,1.704804,4.238148,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,u00,2013-03-30,0.006839,0.885659,0.031844,0.075657,20.411229,0.497835,1.747863,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,u00,2013-03-31,0.076462,0.808346,0.024613,0.090580,83.016935,1.153013,3.684254,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,u00,2013-04-01,0.014352,0.907026,0.014976,0.063647,10.729613,0.149022,0.677181,...,0.033109,0.028555,-3.685911,-1.441327,0.256460,0.178271,0.817709,1.239699,-0.928750,-0.656858
6,6,u00,2013-04-02,0.032226,0.896728,0.040562,0.030484,79.432158,1.118763,3.465933,...,0.029983,0.026664,-1.276126,0.053689,2.678350,-0.101073,-1.341872,0.783184,-2.090354,0.084129
7,7,u00,2013-04-03,0.026512,0.870675,0.027757,0.075056,50.012179,0.704397,2.147938,...,0.030303,0.024355,-0.595930,-0.500915,0.639554,0.455387,0.812368,0.114135,-0.043877,-0.155641
8,8,u00,2013-04-04,0.025930,0.893273,0.023801,0.056996,41.993037,0.583237,1.972396,...,0.029829,0.022588,1.891610,-0.624411,-0.508896,-2.349817,0.056408,0.655691,-0.671674,-0.172612
9,9,u00,2013-04-05,0.019042,0.871879,0.035309,0.073770,34.582094,0.487072,1.651607,...,0.029396,0.021169,-1.105868,-0.732935,-0.146407,0.323550,0.309824,0.066742,-0.012155,-0.489100
10,10,u00,2013-04-06,0.028449,0.861657,0.061682,0.048212,359.602213,5.064820,6.580211,...,0.028361,0.020225,1.161895,6.265587,1.430813,0.140891,0.564492,-0.209900,-0.995088,0.004377
11,11,u00,2013-04-07,0.036371,0.926378,0.011704,0.025547,24.190516,0.340711,1.613796,...,0.026552,0.019202,1.072424,-0.689642,0.297387,-0.647213,0.795952,1.627512,-1.784376,0.511296

In [ ]:
behavior.drop(columns=['Unnamed: 0'],inplace=True)

In [ ]:
behavior.shape

(3216, 44)

In [ ]:
behavior.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3216 entries, 0 to 3215
Data columns (total 43 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   user_id                          3216 non-null   object
 1   date                             3216 non-null   object
 2   Running                          3216 non-null   float64
 3   Stationary                       3216 non-null   float64
 4   Unknown                          3216 non-null   float64
 5   Walking                          3216 non-null   float64
 6   dist_total_km                    3216 non-null   float64
 7   dist_mean_km                     3216 non-null   float64
 8   dist_std_km                      3216 non-null   float64
 9   lat_std                          3216 non-null   float64
 10  lon_std                          3216 non-null   float64
 11  home_points                      3216 non-null   float64
 12  conversation_count               3216 non-null   float64
 13  total_conversation_minutes       3216 non-null   float64
 14  avg_conversation_minutes         3216 non-null   float64
 15  avg_bt_level                     3216 non-null   float64
 16  num_bt_devices                   3216 non-null   float64
 17  sleep_duration                   3216 non-null   float64
 18  sleep_quality                    3216 non-null   float64
 19  sleep_duration_mean              2976 non-null   float64
 20  sleep_duration_std               2976 non-null   float64
 21  dist_total_km_mean               2976 non-null   float64
 22  dist_total_km_std                2976 non-null   float64
 23  conversation_count_mean          2976 non-null   float64
 24  conversation_count_std           2976 non-null   float64
 25  total_conversation_minutes_mean  2976 non-null   float64
 26  total_conversation_minutes_std   2976 non-null   float64
 27  num_bt_devices_mean              2976 non-null   float64
 28  num_bt_devices_std               2976 non-null   float64
 29  Stationary_mean                  2976 non-null   float64
 30  Stationary_std                   2976 non-null   float64
 31  Walking_mean                     2976 non-null   float64
 32  Walking_std                      2976 non-null   float64
 33  Running_mean                     2976 non-null   float64
 34  Running_std                      2976 non-null   float64
 35  sleep_duration_z                 2976 non-null   float64
 36  dist_total_km_z                  2976 non-null   float64
 37  conversation_count_z             2976 non-null   float64
 38  total_conversation_minutes_z     2976 non-null   float64
 39  num_bt_devices_z                 2976 non-null   float64
 40  Stationary_z                     2976 non-null   float64
 41  Walking_z                        2976 non-null   float64
 42  Running_z                        2976 non-null   float64
dtypes: float64(41), object(2)
memory usage: 1.1+ MB

In [ ]:
behavior['date'] = pd.to_datetime(behavior['date'])

In [ ]:
behavior = behavior.loc[behavior['user_id'] != 'u11']

In [ ]:
behavior.drop(columns=['sleep_duration_mean',
       'sleep_duration_std', 'dist_total_km_mean', 'dist_total_km_std',
       'conversation_count_mean', 'conversation_count_std',
       'total_conversation_minutes_mean', 'total_conversation_minutes_std',
       'num_bt_devices_mean', 'num_bt_devices_std', 'Stationary_mean',
       'Stationary_std', 'Walking_mean', 'Walking_std', 'Running_mean',
       'Running_std'],inplace=True)

In [ ]:
behavior.user_id.nunique()

47

In [ ]:
behavior.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3149 entries, 0 to 3215
Data columns (total 27 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   user_id                       3149 non-null   object
 1   date                          3149 non-null   datetime64[ns]
 2   Running                       3149 non-null   float64
 3   Stationary                    3149 non-null   float64
 4   Unknown                       3149 non-null   float64
 5   Walking                       3149 non-null   float64
 6   dist_total_km                 3149 non-null   float64
 7   dist_mean_km                  3149 non-null   float64
 8   dist_std_km                   3149 non-null   float64
 9   lat_std                       3149 non-null   float64
 10  lon_std                       3149 non-null   float64
 11  home_points                   3149 non-null   float64
 12  conversation_count            3149 non-null   float64
 13  total_conversation_minutes    3149 non-null   float64
 14  avg_conversation_minutes      3149 non-null   float64
 15  avg_bt_level                  3149 non-null   float64
 16  num_bt_devices                3149 non-null   float64
 17  sleep_duration                3149 non-null   float64
 18  sleep_quality                 3149 non-null   float64
 19  sleep_duration_z              2914 non-null   float64
 20  dist_total_km_z               2914 non-null   float64
 21  conversation_count_z          2914 non-null   float64
 22  total_conversation_minutes_z  2914 non-null   float64
 23  num_bt_devices_z              2914 non-null   float64
 24  Stationary_z                  2914 non-null   float64
 25  Walking_z                     2914 non-null   float64
 26  Running_z                     2914 non-null   float64
dtypes: datetime64[ns](1), float64(25), object(1)
memory usage: 688.8+ KB

# Output

In [ ]:
output_stress = pd.read_csv('/content/stress_output4.csv')

In [ ]:
output_stress.head()

,Unnamed: 0,user_id,date,stress_level,stress_level_2,stress_category
0,0,u00,2013-03-27,1.0,3.0,Good
1,1,u00,2013-03-28,4.0,2.0,Good
2,2,u00,2013-03-29,4.0,2.0,Good
3,3,u00,2013-03-30,4.0,2.0,Good
4,4,u00,2013-03-31,4.0,2.0,Good

In [ ]:
output_stress.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3216 entries, 0 to 3215
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       3216 non-null   int64
 1   user_id          3216 non-null   object
 2   date             3216 non-null   object
 3   stress_level     1223 non-null   float64
 4   stress_level_2   3149 non-null   float64
 5   stress_category  3216 non-null   object
dtypes: float64(2), int64(1), object(3)
memory usage: 150.9+ KB

In [ ]:
output_stress['date'] = pd.to_datetime(output_stress['date'])

In [ ]:
output_stress.drop(columns = ['Unnamed: 0','stress_level','stress_level_2'],inplace=True)

In [ ]:
output_stress.stress_category.value_counts()

stress_category
Good        2041
Stressed    1175
Name: count, dtype: int64

In [ ]:
output_stress = output_stress.loc[output_stress['user_id'] != 'u11']

In [ ]:
output_stress.stress_category = output_stress.stress_category.replace({'Stressed':1,'Good': 0})

/tmp/ipykernel_427/3172295960.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  output_stress.stress_category = output_stress.stress_category.replace({'Stressed':1,'Good': 0})

In [ ]:
output_stress.stress_category.value_counts()

stress_category
0    2041
1    1108
Name: count, dtype: int64

# MiniRocket

In [ ]:
!pip install sktime

Requirement already satisfied: sktime in /usr/local/lib/python3.12/dist-packages (0.40.1)
Requirement already satisfied: joblib<1.6,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from sktime) (1.5.3)
Requirement already satisfied: numpy<2.4,>=1.21 in /usr/local/lib/python3.12/dist-packages (from sktime) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from sktime) (26.0)
Requirement already satisfied: pandas<2.4.0,>=1.1 in /usr/local/lib/python3.12/dist-packages (from sktime) (2.2.2)
Requirement already satisfied: scikit-base<0.14.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from sktime) (0.13.1)
Requirement already satisfied: scikit-learn<1.8.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from sktime) (1.6.1)
Requirement already satisfied: scipy<2.0.0,>=1.2 in /usr/local/lib/python3.12/dist-packages (from sktime) (1.16.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4.0,>=1.1->sktime) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4.0,>=1.1->sktime) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4.0,>=1.1->sktime) (2025.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<1.8.0,>=0.24->sktime) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<2.4.0,>=1.1->sktime) (1.17.0)

In [ ]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sktime.transformations.panel.rocket import MiniRocket
import warnings
warnings.filterwarnings('ignore')

In [ ]:
merged_df = behavior.merge(output_stress,how = 'inner', on = ['date','user_id'])
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3149 entries, 0 to 3148
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   user_id                       3149 non-null   object
 1   date                          3149 non-null   datetime64[ns]
 2   Running                       3149 non-null   float64
 3   Stationary                    3149 non-null   float64
 4   Unknown                       3149 non-null   float64
 5   Walking                       3149 non-null   float64
 6   dist_total_km                 3149 non-null   float64
 7   dist_mean_km                  3149 non-null   float64
 8   dist_std_km                   3149 non-null   float64
 9   lat_std                       3149 non-null   float64
 10  lon_std                       3149 non-null   float64
 11  home_points                   3149 non-null   float64
 12  conversation_count            3149 non-null   float64
 13  total_conversation_minutes    3149 non-null   float64
 14  avg_conversation_minutes      3149 non-null   float64
 15  avg_bt_level                  3149 non-null   float64
 16  num_bt_devices                3149 non-null   float64
 17  sleep_duration                3149 non-null   float64
 18  sleep_quality                 3149 non-null   float64
 19  sleep_duration_z              2914 non-null   float64
 20  dist_total_km_z               2914 non-null   float64
 21  conversation_count_z          2914 non-null   float64
 22  total_conversation_minutes_z  2914 non-null   float64
 23  num_bt_devices_z              2914 non-null   float64
 24  Stationary_z                  2914 non-null   float64
 25  Walking_z                     2914 non-null   float64
 26  Running_z                     2914 non-null   float64
 27  stress_category               3149 non-null   int64
dtypes: datetime64[ns](1), float64(25), int64(1), object(1)
memory usage: 689.0+ KB

In [ ]:
# Identify feature and target columns
exclude_cols = ['user_id', 'date', 'stress_category']
feature_cols = [col for col in merged_df.columns if col not in exclude_cols]
target_cols = ['stress_category']

print(f"Features: {len(feature_cols)} columns")
print(f"Targets: {target_cols}")
print(f"Merged data shape: {merged_df.shape}")

Features: 25 columns
Targets: ['stress_category']
Merged data shape: (3149, 28)

In [ ]:
def reshape_to_3d(df, feature_cols, target_cols, min_days=14):

    df = df.sort_values(['user_id', 'date'])
    users = df['user_id'].unique()

    X_list = []
    y_list = []
    date_list = []
    valid_users = []

    for user in users:

        user_df = df[df['user_id'] == user]

        # Skip users with insufficient data
        if len(user_df) < min_days:
            continue

        features = user_df[feature_cols].values.T   # (features, days)
        targets = user_df[target_cols].values       # (days, 1)
        dates = user_df['date'].values              # (days,)

        X_list.append(features)
        y_list.append(targets)
        date_list.append(dates)
        valid_users.append(user)

    return X_list, y_list, valid_users, date_list

In [ ]:
X, y, user_ids, date_list = reshape_to_3d(
    merged_df, feature_cols, target_cols
)

In [ ]:
def create_sliding_windows(X_list, y_list, users, dates, window_size=10):

    windows_X = []
    windows_y = []
    meta_user = []
    meta_date = []

    # Iterate per user
    for user_idx, features in enumerate(X_list):

        targets = y_list[user_idx]
        user_dates = dates[user_idx]

        n_days = features.shape[1]  # days for THIS user

        # Skip users that still don't have enough data
        if n_days < window_size:
            continue

        for day in range(window_size, n_days):

            # Extract rolling window
            window = features[:, day-window_size:day]
            target = targets[day]

            windows_X.append(window)
            windows_y.append(target)

            # Save metadata
            meta_user.append(users[user_idx])
            meta_date.append(user_dates[day])

    # Convert to numpy arrays
    X_windows = np.stack(windows_X)
    y_windows = np.stack(windows_y)

    # Convert to (samples, timesteps, features)
    X_windows = np.transpose(X_windows, (0, 2, 1))

    metadata = pd.DataFrame({
        "user_id": meta_user,
        "date": meta_date
    })

    return X_windows, y_windows, metadata

In [ ]:
X_windows, y_windows, metadata = create_sliding_windows(X, y, user_ids, date_list, window_size=10)

In [ ]:
from sklearn.model_selection import GroupShuffleSplit

gss = GroupShuffleSplit(test_size=0.2, random_state=40)

train_idx, test_idx = next(
    gss.split(X_windows, y_windows, groups=metadata['user_id'])
)

X_train = X_windows[train_idx]
X_test = X_windows[test_idx]

y_train = y_windows[train_idx]
y_test = y_windows[test_idx]

meta_train = metadata.iloc[train_idx]
meta_test = metadata.iloc[test_idx]

In [ ]:
metadata.user_id.unique()

array(['u00', 'u01', 'u02', 'u03', 'u04', 'u05', 'u06', 'u07', 'u08',
       'u09', 'u10', 'u12', 'u13', 'u14', 'u15', 'u16', 'u17', 'u18',
       'u19', 'u20', 'u21', 'u22', 'u23', 'u24', 'u25', 'u26', 'u27',
       'u28', 'u29', 'u30', 'u31', 'u32', 'u33', 'u34', 'u35', 'u36',
       'u37', 'u38', 'u39', 'u40', 'u41', 'u42', 'u43', 'u44', 'u45',
       'u46', 'u47'], dtype=object)

In [ ]:
# Check available parameters
print("MiniRocket parameters:", MiniRocket().get_params().keys())

MiniRocket parameters: dict_keys(['max_dilations_per_kernel', 'n_jobs', 'num_kernels', 'random_state'])

In [ ]:

# Phase 1:MiniRocket Transformation

from sktime.transformations.panel.rocket import MiniRocket


num_kernels = 200
max_dilations_per_kernel = 9
window_size = 10

minirocket = MiniRocket(
    num_kernels=num_kernels,
    max_dilations_per_kernel=max_dilations_per_kernel,
    random_state=42,
    n_jobs=-1
)

minirocket.fit(X_train)           # X_train should be (n_samples, timesteps, features)
X_train_mr = minirocket.transform(X_train)
X_test_mr = minirocket.transform(X_test)

print("MiniRocket outputs:", X_train_mr.shape, X_test_mr.shape)




print(f"Original training shape: {X_train.shape}")
print(f"MiniRocket training features: {X_train_mr.shape}")
print(f"MiniRocket test features: {X_test_mr.shape}")

MiniRocket outputs: (2109, 1680) (570, 1680)
Original training shape: (2109, 10, 25)
MiniRocket training features: (2109, 1680)
MiniRocket test features: (570, 1680)

In [ ]:

# FINAL FEATURE SELECTION
import numpy as np
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import mutual_info_classif
from sklearn.ensemble import RandomForestClassifier


def select_features_minirocket(
    X_train, X_test, y_train,
    stage1_k=1100,
    final_k=900,
    use_mutual_info=False,
    random_state=42
):

    X_train_np = np.asarray(X_train)
    X_test_np = np.asarray(X_test)
    y_train_np = np.asarray(y_train).ravel()   # ensure 1D target

    n_features = X_train_np.shape[1]

    # Clamp to available features
    stage1_k = min(stage1_k, n_features)
    final_k = min(final_k, stage1_k)

    # Stage 1: FILTER SELECTION (UNIVARIATE)
    if use_mutual_info:

        scores = mutual_info_classif(
            X_train_np,
            y_train_np,
            discrete_features=False,
            random_state=random_state
        )

    else:
        scores, _ = f_classif(X_train_np, y_train_np)

    scores = np.nan_to_num(scores)

    stage1_idx = np.argsort(scores)[-stage1_k:]

    X_train_f = X_train_np[:, stage1_idx]
    X_test_f = X_test_np[:, stage1_idx]


    # Stage 2: RANDOM FOREST IMPORTANCE
    rf = RandomForestClassifier(
        n_estimators=200,
        max_depth=9,
        min_samples_leaf=2,
        max_features=0.6,
        random_state=random_state,
        n_jobs=-1,
        class_weight="balanced"   # important for stress imbalance
    )

    rf.fit(X_train_f, y_train_np)

    importances = rf.feature_importances_

    stage2_idx = np.argsort(importances)[-final_k:]

    X_train_sel = X_train_f[:, stage2_idx]
    X_test_sel = X_test_f[:, stage2_idx]

    selected_indices = stage1_idx[stage2_idx]

    return X_train_sel, X_test_sel, selected_indices

In [ ]:
# FEATURE SELECTION (FINAL)

X_train_selected, X_test_selected, selected_indices = select_features_minirocket(
    X_train_mr, X_test_mr, y_train, stage1_k=1200, final_k=1000, use_mutual_info=False
)

# Training

In [ ]:
Phase 3: Train & Evaluate Individual Models

from xgboost import XGBClassifier
from sklearn.metrics import classification_report, accuracy_score
import numpy as np

print("=== TRAINING INDIVIDUAL MODELS ===\n")
# Convert y to numpy (1D)
y_train_np = np.array(y_train).ravel()
y_test_np = np.array(y_test).ravel()
num_positive = np.sum(y_train_np == 1)   # Stressed
num_negative = np.sum(y_train_np == 0)   # Good

scale_pos_weight = num_negative / num_positive

print("scale_pos_weight:", scale_pos_weight)

# Define models with optimized parameters
models = {
    # 'RandomForest': RandomForestClassifier(
    #     n_estimators=200,
    #     max_depth=8,
    #     min_samples_split=8,
    #     min_samples_leaf=4,
    #     max_features=0.6,
    #     random_state=42,
    #     n_jobs=-1,
    #     class_weight=None
    # ),

    # 'GradientBoosting': GradientBoostingClassifier(
    #     n_estimators=200,
    #     max_depth=3,
    #     learning_rate=0.05,
    #     subsample=0.8,
    #     min_samples_split=10,
    #     random_state=42
    # ),

    'XGBoost': XGBClassifier(
        n_estimators=250,
        max_depth=2,
        learning_rate=0.03,
        subsample=0.75,
        colsample_bytree=0.75,
        random_state=42,
        n_jobs=-1,
        reg_alpha=1,
        reg_lambda=2,
        tree_method='auto',
        eval_metric='logloss',
        scale_pos_weight=scale_pos_weight
    )
}


# ------------------------------------------------
# Store results
# ------------------------------------------------
model_results = {}
predictions = {}

for name, model in models.items():
    prob=[0.35]
    print(f"Training {name}...")
    for i in prob:
      print(f'for threshold = {i}')
      # Fit model
      model.fit(X_train_selected, y_train_np)

      # Predictions
      y_pred_train = model.predict(X_train_selected)

      # y_pred_test = model.predict(X_test_selected)
      probs = model.predict_proba(X_test_selected)[:,1]
      y_pred_test = (probs > i).astype(int)

      # Accuracy
      train_acc = accuracy_score(y_train_np, y_pred_train)
      test_acc = accuracy_score(y_test_np, y_pred_test)

      # Save results
      model_results[name] = {
          'model': model,
          'train_accuracy': train_acc,
          'test_accuracy': test_acc
      }

      predictions[name] = y_pred_test

      # ------------------------------------------------
      # Print results
      # ------------------------------------------------
      print(f"Train Accuracy: {train_acc:.4f}")
      print(f"Test Accuracy:  {test_acc:.4f}\n")

      print("Classification Report (Test):")
      print(classification_report(
          y_test_np,
          y_pred_test,
          target_names=["Stressed", "Good"]
      ))
      print("="*50)

=== TRAINING INDIVIDUAL MODELS ===

scale_pos_weight: 1.9455307262569832
Training XGBoost...
for threshold = 0.35
Train Accuracy: 0.7776
Test Accuracy:  0.6298

Classification Report (Test):
              precision    recall  f1-score   support

    Stressed       0.64      0.63      0.64       293
        Good       0.62      0.63      0.62       277

    accuracy                           0.63       570
   macro avg       0.63      0.63      0.63       570
weighted avg       0.63      0.63      0.63       570

==================================================

# model extraction

In [ ]:
import joblib

# Save MiniRocket transformer (already fitted)
joblib.dump(minirocket, "minirocket.pkl")

# Save selected feature indices
joblib.dump(selected_indices, "selected_indices.pkl")

# Save trained XGBoost model
joblib.dump(model, "xgboost_stress_model.pkl")

print("All components saved successfully.")

All components saved successfully.

In [ ]:
pipeline = {
    "minirocket": minirocket,
    "selected_indices": selected_indices,
    "model": model
}

joblib.dump(pipeline, "pipeline.pkl")